remote_theme: "mmistakes/minimal-mistakes@4.24.0"
<!-- HEADER -->
<div id="header_wrap" class="outer">
    <header class="inner">
      <a id="forkme_banner" href="{{ site.github.repository_url }}">View on GitHub</a>
      <h1 id="project_title">{{ site.title | default: Learn stats }}</h1>
      <h2 id="project_tagline">{{ site.description | default: To help understand stats}}</h2>
      {% if site.show_downloads %}
        <section id="downloads">
          <a class="zip_download_link" href="{{ site.github.zip_url }}">Download this project as a .zip file</a>
          <a class="tar_download_link" href="{{ site.github.tar_url }}">Download this project as a tar.gz file</a>
        </section>
      {% endif %}
      {% include nav.html %}
    </header>
</div>
